<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mil" nsURI="http://mdsd.edu/mil/1.0" nsPrefix="mil">
  <eClassifiers xsi:type="ecore:EClass" name="MILModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoadInstruction" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StoreInstruction" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="registerReference" eType="#//RegisterReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="MulInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="DivInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="NegInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="EqInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="NeqInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="LtInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="LeqInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="GtInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeqInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="JumpInstruction" abstract="true" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" lowerBound="1" eType="#//LabelInstruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JmpInstruction" eSuperTypes="#//JumpInstruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="JpcInstruction" eSuperTypes="#//JumpInstruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalInstruction" eSuperTypes="#//JumpInstruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="RetInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="LabelInstruction" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YldInstruction" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrtInstruction" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InpInstruction" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerBound" eType="#//ConstantInteger"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperBound" eType="#//ConstantInteger"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrInstruction" eSuperTypes="#//PrtInstruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantInteger" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rawValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegisterReference" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
